
name: Make and Publish to Github

on: push

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build-on-win:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --network-timeout 600000
      - name: Publish
        run: yarn run publish
